### ISSUE TITLE
Advanced loggers

### ISSUE THREAD

**Issue by danielgafni** [google/evojax#11]
It would be nice to use `Tensorboard` or any other advanced logging tool with `evojax`. 
Looks like it should be straightforward to allow the user to implement a `log_reward` function that could be passed to the trainer.

I'm willing to implement this in a PR.

**Comment by lerrytang** [comment]
Hi, thanks for the suggestion, it sounds great and I'm looking forward to your PR.
One principle to keep in mind is that we try to make EvoJAX have few dependencies.
