### ISSUE TITLE
[Question] Use of parameter `input_data` in function `step_once` defined in `sim_mgr`

### ISSUE THREAD

**Issue by MaximilienLC** [google/evojax#14]
Hi, I was wondering about the use of parameter `input_data ` in the `step_once` function as it does not appear to be getting used.

https://github.com/google/evojax/blob/55221374f46ed3c28fc4ce061e70a1d0b25586e8/evojax/sim_mgr.py#L140

**Comment by lerrytang** [comment]
It is a dummy placeholder in this case.
This is required by the func signature when using `jax.lax.scan`, you can see more from this [page](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html).

**Comment by MaximilienLC** [comment]
Thanks!
