### ISSUE TITLE
Evolving topology of NN

### ISSUE THREAD

**Issue by TheMightiestCarrot** [google/evojax#54]
Hey guys,

amazing work! Quick question, is it possible to also evolve topology of networks using your framework? Like NEAT does?

**Comment by lerrytang** [comment]
Hi, thanks for the question.
Although we don't have an example in the repo yet, it is possible to implement NEAT in evojax.
I'll put this in my TODO list and release an example early next year.

**Comment by TheMightiestCarrot** [comment]
thanks for answer, here are some repositories for inspiration:
https://github.com/uber-research/PyTorch-NEAT
https://github.com/uber-research/deep-neuroevolution
https://github.com/CodeReclaimers/neat-python

https://github.com/nnaisense/evotorch (even though its not NEAT)

**Comment by jsykes** [comment]
Seeing this marked as completed had me thinking there was one added.
