### ISSUE TITLE
high dimensional parametric search

### ISSUE THREAD

**Issue by Agnes233** [google/evojax#55]
I'm trying to use evojax to evolve my model parameters. I found that the algorithm only accepts the parameter num_dims as the dimension, whether it can only be int type here? If I want to evolve multidimensional parameters, such as [1000x1000] data, how can I do it? Thanks!

**Comment by Agnes233** [comment]
Thank you for your answer. I have tried to call CMA_ES and set num_dims=1000000, an error would be reported:



I don't know what I did wrong, looking forward to your reply!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/evojax"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月14日(星期三) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/evojax] high dimensional parametric search (Issue #55)





 
Hi, thanks for the question.
 In your case, you can simply specify param_size=1000000 and reshape the result from algo.ask() to $1000\times1000$.

**Comment by lerrytang** [comment]
CMA_ES does not work well with large parameter spaces due to the large memory needed by the covariance matrix.
Is your error memory related? Can you try other algos such as PGPE or ARS?

**Comment by Agnes233** [comment]
It works, thanks for your reply! 
What is the maximum number of parameters that evojax can accept?

**Comment by lerrytang** [comment]
evojax does not put limitation on the number of learnable parameters, however your GPU memory is limited.
If you want to evolve a large number of parameters on a GPU with limited memory, reducing the population size will avoid memory errors at the cost of suboptimal solutions (well, they are all suboptimal, so more suboptimal)
