### ISSUE TITLE
AssertionError for OpenES

### ISSUE THREAD

**Issue by pigozzif** [google/evojax#56]
When I try to instantiate OpenES from `open_es.py`, I get the following error message:
<img width="841" alt="Schermata 2022-12-15 alle 20 23 59" src="https://user-images.githubusercontent.com/43779861/207948958-cbe73e00-cbed-4c0d-8ad7-baff6c5a0c1d.png">
I traced back the problem to line 110 in `open_es.py`, where both `centered_rank` and `z_score` arguments are set to True:
<img width="600" alt="Schermata 2022-12-15 alle 20 26 01" src="https://user-images.githubusercontent.com/43779861/207949324-5786fb9a-916b-439d-af80-95c7318f6e22.png">
But line 26 of FitnessShaper class from `evosax/utils/reshape_fitness.py` says that 
<img width="530" alt="Schermata 2022-12-15 alle 20 26 49" src="https://user-images.githubusercontent.com/43779861/207949453-c567311c-bde5-449d-ade4-f017cf92c4f4.png">
How to get around this issue?

**Comment by lerrytang** [comment]
@RobertTLange Do you mind taking a look at this issue?

**Comment by RobertTLange** [comment]
Should be fixed in PR #57. Sorry for the hick-up!

**Comment by lerrytang** [comment]
@RobertTLange Thanks for the fix!
@pigozzif I've merged the PR, can you confirm it fixes your problem?

**Comment by pigozzif** [comment]
Dear all,
the PR fixes my problem. Thank you very much for the support!
Best regards,

Federico Pigozzi
